### ISSUE TITLE
The 'Download Videos' button is clickable when you open the app

### ISSUE THREAD

**Issue by almeidx** [Timber1900/WebDL#30]
**Describe the issue**
If you click the 'Download Videos' button is clickable when you first open the app, the button then becomes non-clickable even if you add videos, meaning you can't download videos unless if you use the dropdown menu.

**Screenshots**
no

**Comment by Timber1900** [comment]
Fixed in 629b9c3d734dbf7850c0bfbff7a46ccc1e18db2c
